### ISSUE TITLE
jdk.internal.crac.mirror.impl.CheckpointOpenResourceException: FD fd=28 type=unknown path=anon_inode:[eventpoll]

### ISSUE THREAD

**Issue by gluo1130** [CRaC/docs#26]
How to solve the error jdk.internal.crac.mirror.impl.CheckpointOpenResourceException: FD fd=28 type=unknown path=anon_inode:[eventpoll]

When currently planning to add a checkpoint, the following exception was thrown, and the stack is as follows:
```
zulu17.48.15-ca-crac-jdk17.0.10-linux_x64/bin/jcmd cloudnative-consumer-2023.0.0-SNAPSHOT.jar JDK.checkpoint
5708:
An exception during a checkpoint operation:
jdk.internal.crac.mirror.CheckpointException
	Suppressed: java.nio.channels.IllegalSelectorException
		at java.base/sun.nio.ch.EPollSelectorImpl.beforeCheckpoint(EPollSelectorImpl.java:395)
		at java.base/jdk.internal.crac.mirror.impl.AbstractContext.invokeBeforeCheckpoint(AbstractContext.java:43)
		at java.base/jdk.internal.crac.mirror.impl.AbstractContext.beforeCheckpoint(AbstractContext.java:58)
		at java.base/jdk.internal.crac.mirror.impl.BlockingOrderedContext.beforeCheckpoint(BlockingOrderedContext.java:64)
		at java.base/jdk.internal.crac.mirror.impl.AbstractContext.invokeBeforeCheckpoint(AbstractContext.java:43)
		at java.base/jdk.internal.crac.mirror.impl.AbstractContext.beforeCheckpoint(AbstractContext.java:58)
		at java.base/jdk.internal.crac.mirror.Core.checkpointRestore1(Core.java:153)
		at java.base/jdk.internal.crac.mirror.Core.checkpointRestore(Core.java:286)
		at java.base/jdk.internal.crac.mirror.Core.checkpointRestoreInternal(Core.java:299)
	Suppressed: jdk.internal.crac.mirror.impl.CheckpointOpenResourceException: FD fd=28 type=unknown path=anon_inode:[eventpoll]
		at java.base/jdk.internal.crac.mirror.Core.translateJVMExceptions(Core.java:117)
		at java.base/jdk.internal.crac.mirror.Core.checkpointRestore1(Core.java:188)
		at java.base/jdk.internal.crac.mirror.Core.checkpointRestore(Core.java:286)
		at java.base/jdk.internal.crac.mirror.Core.checkpointRestoreInternal(Core.java:299)
	Suppressed: jdk.internal.crac.mirror.impl.CheckpointOpenResourceException: FD fd=29 type=unknown path=anon_inode:[eventfd]
		at java.base/jdk.internal.crac.mirror.Core.translateJVMExceptions(Core.java:117)
		at java.base/jdk.internal.crac.mirror.Core.checkpointRestore1(Core.java:188)
		at java.base/jdk.internal.crac.mirror.Core.checkpointRestore(Core.java:286)
		at java.base/jdk.internal.crac.mirror.Core.checkpointRestoreInternal(Core.java:299)
```

**Comment by rvansa** [comment]
You should see a log message suggesting to add `-Djdk.crac.collect-fd-stacktraces=true` - this will point to the stack trace where the FD is created. With this information you can raise a request to springboot to fix the CRaC support (assuming that this is opened from springboot libraries).

**Comment by gluo1130** [comment]
> You should see a log message suggesting to add `-Djdk.crac.collect-fd-stacktraces=true` - this will point to the stack trace where the FD is created. With this information you can raise a request to springboot to fix the CRaC support (assuming that this is opened from springboot libraries).

I added -Djdk.crac.collect-fd-stacktraces=true and the startup command and jcmd are as follows
```
zulu17.48.15-ca-crac-jdk17.0.10-linux_x64/bin/java -Djdk.crac.resource-policies=crac.yaml  -Djdk.crac.collect-fd-stacktraces=true  -XX:CRaCCheckpointTo=./tmp_checkpoint -jar 3.2.0/cloudnative-consumer-2023.0.0-SNAPSHOT.jar > log/jdk-start-zulu.log &

zulu17.48.15-ca-crac-jdk17.0.10-linux_x64/bin/jcmd cloudnative-consumer-2023.0.0-SNAPSHOT.jar JDK.checkpoint
```
Among them crac.yaml configuration
```
type: socket
localAddress: *
action: ignore
---
type: file
path: /opt
action: ignore
---
type: file
path: /tmp
action: ignore
---
type: file
path: log/*
action: reopen
---
type: file
path: log/formula/*
action: reopen
---
type: file
path: *
action: reopen
---
type: pipe
action: ignore
```

An error is still reported when executing jcmd. The error log is as follows:
```
2024-04-16T16:30:29.284+08:00  INFO [cpdinf-cloudnative-consumer,,,] 24480 --- [cloudnative-consumer] [Attach Listener] jdk.crac                                 : Starting checkpoint
2024-04-16T16:30:29.292+08:00  INFO [cpdinf-cloudnative-consumer,,,] 24480 --- [cloudnative-consumer] [Attach Listener] c.b.c.s.transport.netty.NettyServer      : Shutdown starlight server gracefully start
2024-04-16T16:30:29.292+08:00  INFO [cpdinf-cloudnative-consumer,,,] 24480 --- [cloudnative-consumer] [Attach Listener] c.b.c.s.transport.netty.NettyServer      : Notify server shutting down to clients begin
2024-04-16T16:30:29.292+08:00  INFO [cpdinf-cloudnative-consumer,,,] 24480 --- [cloudnative-consumer] [Attach Listener] c.b.c.s.transport.netty.NettyServer      : Notify server shutting down end, cost 0 clients 0
2024-04-16T16:30:29.292+08:00  INFO [cpdinf-cloudnative-consumer,,,] 24480 --- [cloudnative-consumer] [Attach Listener] c.b.c.s.transport.netty.NettyServer      : Wait for quiet period pass 10s
2024-04-16T16:30:29.292+08:00  INFO [cpdinf-cloudnative-consumer,,,] 24480 --- [cloudnative-consumer] [egisterWorker-1] c.b.c.s.s.s.r.StarlightRegisterListener  : Deregister server instance null:8666 start
2024-04-16T16:30:29.292+08:00  INFO [cpdinf-cloudnative-consumer,,,] 24480 --- [cloudnative-consumer] [egisterWorker-1] c.b.c.g.d.r.GravityServiceRegistry       : Deregistering service cloudnative-consumer, host:10.25.73.128:8666
2024-04-16T16:30:29.293+08:00  INFO [cpdinf-cloudnative-consumer,,,] 24480 --- [cloudnative-consumer] [egisterWorker-1] c.b.c.gravity.client.beat.BeatScheduler  : Stop heartbeat task for endpoint id: cpdinf-cloudnative-consumer-10.25.73.128-8666
2024-04-16T16:30:36.613+08:00  INFO [cpdinf-cloudnative-consumer,,,] 24480 --- [cloudnative-consumer] [egisterWorker-1] c.b.c.g.d.r.GravityServiceRegistry       : Deregistered service cloudnative-consumer, host:10.25.73.128:8666
2024-04-16T16:30:36.613+08:00  INFO [cpdinf-cloudnative-consumer,,,] 24480 --- [cloudnative-consumer] [egisterWorker-1] c.b.c.s.s.s.r.StarlightRegisterListener  : Deregister server instance null:8666 success
2024-04-16T16:30:39.293+08:00  INFO [cpdinf-cloudnative-consumer,,,] 24480 --- [cloudnative-consumer] [Attach Listener] c.b.c.s.transport.netty.NettyServer      : Netty pending tasks num is 0
2024-04-16T16:30:39.293+08:00  INFO [cpdinf-cloudnative-consumer,,,] 24480 --- [cloudnative-consumer] [Attach Listener] c.b.c.s.transport.netty.NettyServer      : NettyServer has processed all requests, gracefully shutdown.
2024-04-16T16:30:39.295+08:00  INFO [cpdinf-cloudnative-consumer,,,] 24480 --- [cloudnative-consumer] [Attach Listener] c.b.c.s.transport.netty.NettyServer      : Shutdown starlight server gracefully end
JVM: invalid info for restore provided: queued code -1
2024-04-16T16:30:39.601+08:00  INFO [cpdinf-cloudnative-consumer,,,] 24480 --- [cloudnative-consumer] [Attach Listener] o.s.c.support.DefaultLifecycleProcessor  : Restarting Spring-managed lifecycle beans after JVM restore
2024-04-16T16:30:39.648+08:00  INFO [cpdinf-cloudnative-consumer,,,] 24480 --- [cloudnative-consumer] [Attach Listener] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 8080 (http) with context path ''
2024-04-16T16:30:39.657+08:00  INFO [cpdinf-cloudnative-consumer,,,] 24480 --- [cloudnative-consumer] [Attach Listener] o.s.c.support.DefaultLifecycleProcessor  : Spring-managed lifecycle restart completed (restored JVM running for -1 ms)
An exception during a checkpoint operation:
jdk.internal.crac.mirror.CheckpointException
	Suppressed: java.lang.RuntimeException: Native checkpoint failed.
		at java.base/jdk.internal.crac.mirror.Core.translateJVMExceptions(Core.java:109)
		at java.base/jdk.internal.crac.mirror.Core.checkpointRestore1(Core.java:188)
		at java.base/jdk.internal.crac.mirror.Core.checkpointRestore(Core.java:286)
		at java.base/jdk.internal.crac.mirror.Core.checkpointRestoreInternal(Core.java:299)
```

**Comment by gluo1130** [comment]
> You should see a log message suggesting to add `-Djdk.crac.collect-fd-stacktraces=true` - this will point to the stack trace where the FD is created. With this information you can raise a request to springboot to fix the CRaC support (assuming that this is opened from springboot libraries).

I also tried to use -Dspring.context.checkpoint=onRefresh to configure startup and add automatic checkpoint
```
zulu17.48.15-ca-crac-jdk17.0.10-linux_x64/bin/java -Djdk.crac.resource-policies=crac.yaml -Dspring.context.checkpoint=onRefresh -Djdk.crac.collect-fd-stacktraces=true  -XX:CRaCCheckpointTo=./tmp_checkpoint -jar 3.2.0/cloudnative-consumer-2023.0.0-SNAPSHOT.jar > log/jdk-start-zulu.log &
```
The error log of log/jdk-start-zulu.log is as follows
```
2024-04-16T16:39:00.447+08:00  INFO [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] o.s.c.support.DefaultLifecycleProcessor  : Triggering JVM checkpoint/restore
2024-04-16T16:39:00.458+08:00  INFO [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] jdk.crac                                 : Starting checkpoint
2024-04-16T16:39:00.462+08:00  INFO [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] jdk.crac                                 : /root/luogang05/crac/3.2.0/cloudnative-consumer-2023.0.0-SNAPSHOT.jar is recorded as always available on restore
2024-04-16T16:39:00.782+08:00  WARN [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] jdk.crac                                 : Socket sun.nio.ch.ServerSocketChannelImpl[/[0:0:0:0:0:0:0:0]:8666] was not closed by the application.
2024-04-16T16:39:00.782+08:00  INFO [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] jdk.crac                                 : To suppress the warning above use 'warn: false' in the resource policy.
2024-04-16T16:39:00.782+08:00  WARN [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] jdk.crac                                 : Socket Socket[addr=/10.174.69.57,port=9044,localport=60904] was not closed by the application.
2024-04-16T16:39:00.783+08:00  WARN [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] jdk.crac                                 : Socket Socket[addr=/10.174.69.57,port=9044,localport=60892] was not closed by the application.
2024-04-16T16:39:00.783+08:00  WARN [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] jdk.crac                                 : Socket Socket[addr=gravitation.baidu-int.com/10.11.149.249,port=80,localport=53516] was not closed by the application.
2024-04-16T16:39:00.784+08:00  WARN [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] jdk.crac                                 : File log/sal.log was not closed by the application.
2024-04-16T16:39:00.784+08:00  WARN [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] jdk.crac                                 : File log/formula/redis.log was not closed by the application.
2024-04-16T16:39:00.784+08:00  WARN [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] jdk.crac                                 : File log/error.log was not closed by the application.
2024-04-16T16:39:00.785+08:00  WARN [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] jdk.crac                                 : File log/formula/starlight.log was not closed by the application.
2024-04-16T16:39:00.785+08:00  WARN [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] jdk.crac                                 : File log/invoke.log was not closed by the application.
2024-04-16T16:39:00.785+08:00  WARN [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] jdk.crac                                 : File log/formula/gravity.log was not closed by the application.
2024-04-16T16:39:00.785+08:00  WARN [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] jdk.crac                                 : File log/formula/smartjdbc.log was not closed by the application.
2024-04-16T16:39:00.786+08:00  WARN [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] jdk.crac                                 : File log/access.log was not closed by the application.
2024-04-16T16:39:00.786+08:00  WARN [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] jdk.crac                                 : File log/default.log was not closed by the application.
2024-04-16T16:39:00.786+08:00  WARN [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] jdk.crac                                 : File log/biz.log was not closed by the application.
2024-04-16T16:39:00.900+08:00  INFO [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] o.s.c.support.DefaultLifecycleProcessor  : Restarting Spring-managed lifecycle beans after JVM restore
2024-04-16T16:39:00.900+08:00  WARN [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to take CRaC checkpoint on refresh
2024-04-16T16:39:00.992+08:00  INFO [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] c.b.c.s.s.s.r.StarlightRegisterListener  : Shutdown the Executor pool for StarlightRegisterListener
2024-04-16T16:39:01.004+08:00  INFO [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] c.b.c.gravity.client.beat.BeatScheduler  : HeartBeat task stopped
2024-04-16T16:39:01.004+08:00  INFO [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] c.b.c.gravity.client.naming.ServerProxy  : AsyncHttpClient is closed in ServerProxy
2024-04-16T16:39:01.005+08:00  INFO [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] c.b.c.gravity.client.beat.BeatScheduler  : HeartBeat task stopped
2024-04-16T16:39:01.005+08:00  INFO [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] c.b.c.gravity.client.naming.ServerProxy  : AsyncHttpClient is closed in ServerProxy
2024-04-16T16:39:01.005+08:00  INFO [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] .c.s.b.a.r.FileConfigRefreshEventEmitter : FileConfigRefreshEventEmitter destroyed
2024-04-16T16:39:01.260+08:00  INFO [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2024-04-16T16:39:01.279+08:00  WARN [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [pool-2-thread-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@17.0.10/jdk.internal.misc.Unsafe.park(Native Method)
 java.base@17.0.10/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
 java.base@17.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672)
 java.base@17.0.10/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
 java.base@17.0.10/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
 java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
 java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
 java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 java.base@17.0.10/java.lang.Thread.run(Thread.java:840)
2024-04-16T16:39:01.320+08:00  INFO [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] .s.b.a.l.ConditionEvaluationReportLogger :

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-04-16T16:39:01.346+08:00 ERROR [cpdinf-cloudnative-consumer,,,] 30892 --- [cloudnative-consumer] [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Failed to take CRaC checkpoint on refresh
	at org.springframework.context.support.DefaultLifecycleProcessor$CracDelegate.checkpointRestore(DefaultLifecycleProcessor.java:534)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:193)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:965)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:619)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:753)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:455)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:323)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1342)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1331)
	at com.baidu.cloud.demo.consumer.CloudnativeConsumerApp.main(CloudnativeConsumerApp.java:17)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
	at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58)
Caused by: org.crac.CheckpointException: null
	at org.crac.Core$Compat.checkpointRestore(Core.java:144)
	at org.crac.Core.checkpointRestore(Core.java:237)
	at org.springframework.context.support.DefaultLifecycleProcessor$CracDelegate.checkpointRestore(DefaultLifecycleProcessor.java:528)
	... 17 common frames omitted
	Suppressed: java.nio.channels.IllegalSelectorException: null
		at java.base/sun.nio.ch.EPollSelectorImpl.beforeCheckpoint(EPollSelectorImpl.java:395)
		at java.base/jdk.internal.crac.mirror.impl.AbstractContext.invokeBeforeCheckpoint(AbstractContext.java:43)
		at java.base/jdk.internal.crac.mirror.impl.AbstractContext.beforeCheckpoint(AbstractContext.java:58)
		at java.base/jdk.internal.crac.mirror.impl.BlockingOrderedContext.beforeCheckpoint(BlockingOrderedContext.java:64)
		at java.base/jdk.internal.crac.mirror.impl.AbstractContext.invokeBeforeCheckpoint(AbstractContext.java:43)
		at java.base/jdk.internal.crac.mirror.impl.AbstractContext.beforeCheckpoint(AbstractContext.java:58)
		at java.base/jdk.internal.crac.mirror.Core.checkpointRestore1(Core.java:153)
		at java.base/jdk.internal.crac.mirror.Core.checkpointRestore(Core.java:286)
		at java.base/jdk.internal.crac.mirror.Core.checkpointRestore(Core.java:265)
		at jdk.crac/jdk.crac.Core.checkpointRestore(Core.java:72)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at org.crac.Core$Compat.checkpointRestore(Core.java:141)
		... 19 common frames omitted
	Suppressed: jdk.internal.crac.mirror.impl.CheckpointOpenResourceException: FD fd=28 type=unknown path=anon_inode:[eventpoll]
		at java.base/jdk.internal.crac.mirror.Core.translateJVMExceptions(Core.java:117)
		at java.base/jdk.internal.crac.mirror.Core.checkpointRestore1(Core.java:188)
		at java.base/jdk.internal.crac.mirror.Core.checkpointRestore(Core.java:286)
		at java.base/jdk.internal.crac.mirror.Core.checkpointRestore(Core.java:265)
		at jdk.crac/jdk.crac.Core.checkpointRestore(Core.java:72)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at org.crac.Core$Compat.checkpointRestore(Core.java:141)
		... 19 common frames omitted
	Suppressed: jdk.internal.crac.mirror.impl.CheckpointOpenResourceException: FD fd=29 type=unknown path=anon_inode:[eventfd]
		at java.base/jdk.internal.crac.mirror.Core.translateJVMExceptions(Core.java:117)
		at java.base/jdk.internal.crac.mirror.Core.checkpointRestore1(Core.java:188)
		at java.base/jdk.internal.crac.mirror.Core.checkpointRestore(Core.java:286)
		at java.base/jdk.internal.crac.mirror.Core.checkpointRestore(Core.java:265)
		at jdk.crac/jdk.crac.Core.checkpointRestore(Core.java:72)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at org.crac.Core$Compat.checkpointRestore(Core.java:141)
		... 19 common frames omitted
```

**Comment by rvansa** [comment]
Oh sorry, I did not notice that the error is coming from the native FD detection (rather than from Java counterpart). In that case the system property can't trace it, and policies won't be applied - Java part simply won't know about the FD. In that case I usually debug with `strace -f -k` to see where the FD is opened: https://github.com/CRaC/docs/blob/master/debugging.md#file-descriptors-in-native-code . The dump would fail afterwards (as both strace and CRIU use ptrace on the process and there can be only one tracer) but it won't matter for debugging.

In your second comment you got over the native FD checks in CRaC (I guess that policies made the FD ignored), but it failed in CRIU - it didn't know how to reliably persist an open socket.

**Comment by tzvetkovg** [comment]
any way to have the descriptor policy be applied to native FD open files rather Java only processes?

**Comment by rvansa** [comment]
Not at this point.

Architecturally, we want to apply the policies on the resource level - e.g. `FileOutputStream`, not straight on the `FileDescriptor` (the fact that we support FD policies even in FileDescriptor class is rather a last line of defense than a preferred way). So technically the native code could consult FD policies upon detection of open FD, but it doesn't fit well into the picture.

Have you figured out what resource does open the epollfd? Could that be Netty? I've tried to [add automatic close there](https://github.com/netty/netty/pull/13308) but the dependency to `org.crac` was not welcome, so Spring might need to invoke [methods introduced in another PR](https://github.com/netty/netty/pull/13430).

**Comment by tzvetkovg** [comment]
In the lambdas I am testing we've got AWS SSM, MongoDB and Kafka and by the looks of it the sockets don't get closed for the snapshot to be taken as I am getting opensocket exceptions. When I use a file descriptor to close all sockets I get the same generic **CheckpointOpenResourceException: FD fd=29 type=unknown path=anon_inode:[eventfd]** error so I don't know what file is still open? So not sure how I can deal with closing all open files & sockets properly before the snapshot to be taken?

**Comment by rvansa** [comment]
@tzvetkovg It is the application responsible for closing those FD - the configurable policies is rather a workaround for some usecases, not a solution that should do it all. So, to reiterate it's application responsibility to close it => probably task for Springboot guys.
Did you have any chance to `strace` the application to figure out where the FD 29 comes from?

**Comment by tzvetkovg** [comment]
sorry but that's making CRAC quite limited/unusable for complex APPS using spring boot, kafka, mongoDB etc. as closing of the open socket/files functionality is not supported out of the box and by the looks of it spring boot hasn't yet implemented any mechanisms to do so automatically?

**Comment by rvansa** [comment]
Closing e.g. a socket to the database transparently to the application (or to the framework) is something that's practically impossible to do reliably; you'd just blow the application up and hope that it survives that sort of interruption.

Can you put up a minimalistic application that demonstrates your problem? We have a good relationship with Springboot folks, so if we can pinpoint it we can cooperate to fix it in there.
